### PR TITLE
increase peerDep/devDep range for react and bump enzyme

### PR DESCRIPTION
**Pull request by brucewpaul**
This pr updates react and related packages so that react16 is
supported. Enzyme and related packages are also bumped to support
react16. We also configure enzyme to work with whichever react is
currently installed.

### CODE REVIEW

**Comment by brucewpaul** [comment]
this pr addresses https://github.com/airbnb/react-with-direction/issues/1

**Review by ljharb — APPROVED** [review]

**Comment by brucewpaul** [comment]
@ljharb it seems like the extraneous packages are throwing an error. I remember you saying that they weren't supposed to. Thoughts?

**Review by ljharb — APPROVED** [review]

**Comment by ljharb** [comment]
@brucewpaul https://github.com/airbnb/react-with-direction/blob/master/.travis.yml#L7 runs `npm ls`; are you sure that the only issue is extraneous packages?

**Comment by brucewpaul** [comment]
@ljharb there was a typo in the react:16 script, but other then that, I ran `rm -rf node_modules && npm install && sh install-relevant-react.sh` (with manually changing the default react version) and they all install fine, pass tests, but when I `npm ls`, I get the `npm ERR! extraneous` error

**Comment by ljharb** [comment]
I guess temporarily let's comment out the `npm ls` command in travis.yml; we can restore it after we build a better solution for multi-react/enzyme testing (let's talk more about that this week)

**Pull request merged**
